### PR TITLE
Add automatic fire

### PR DESCRIPTION
**Pull request by coderunner**
Added a new checkbox on the modifier dialog only if the weapon is automatic.

Screen Shot 2022-05-19 at 4 50 27 PM

If automatic fire is used, allow to specify the number of 1 to ignore (to take into account high capacity weapon and machine gunner talent).

Screen Shot 2022-05-19 at 4 50 39 PM

Initial roll where we can see the extra rolls for the automatic fire.
Screen Shot 2022-05-19 at 4 50 52 PM

Prayer bonuses are only applied to the skill roll (not the automatic fire roll), but automatic fire dices are rerolled is needed.

Screen Shot 2022-05-19 at 4 51 07 PM

### CODE REVIEW

**Comment by AlexOkafor** [comment]
@coderunner A question and a UX thought:
- Is there some side effect or rule exception that would warrant ignoring 1s when doing automatic rolls?
- UX idea: instead of just rolling all the dice automatically, having a "Roll automatic fire dice" button above push roll. It rolls 1 dice at a time updating the result. Allowing you to either keep rolling dice or stop prematurely. It then becomes disabled once you roll a 1. This was my take on the rules regarding having players roll one at a time for suspense.

There's a -2 modifier to the attack roll the player must include on there own iirc. This isn't ideal but tbh the attack roll dialog I need to re-design to accommodate some of these scenarios so it's more clear to the user what is going on.

**Comment by AlexOkafor** [comment]
To be clear I don't think the auto fire needs re-implementation. It works great as is! Just soliciting thoughts for future enhancements.

**Comment by coderunner** [comment]
Rebased the PR. Let me know if you want me to change anything.

**Comment by AlexOkafor** [comment]
> 1. Yes. There is a talent (machine gunner) and a weapon feature (high capacity) that both allows you to ignore a 1 (so possibly ignore two 1s if you get both).

Perfect! Thanks for the clarification.

**Pull request merged**
