### PR TITLE
Feature: Roll Ship Weapons

### LINKED ISSUE #191: [Enhancement Request] Roll ship weapons like character weapons?
Would it be possible to directly roll ship weapons with all values, analogous to the dice rolls for characters?

### PR DESCRIPTION
**Pull request by gkahn84**
This adds the option to roll ship weapons from the ship sheet just as you can roll personal weapons from the character sheet.

- Adds new button in weapon module template (will be active only if user is GM oder gunner of the ship)
- Includes gunner stats, weapon bonus and modifier dialog option in roll
- Posts chat message with roll result

It includes a modified color scheme for the module buttons that I would like to propose:
  - The "enabled" module button keeps the light green color
  - The "disabled" button gets a gray color instead of red (since red should usually indicate danger or errors and gray usually indicates a disabled state)
  - The "fire" button gets the red color (since it can safely be considered dangerous to fire a weapon and also on real life weapon systems the button is usually red...at least in movies :-D)

The logic that enables/disables the fire button currently does not include gunner EP considerations. For this we would have to be able to distinguish the weapons in more detail since there are weapons (e.g. torpedos and mines) that don't need EP and others that do. Could be hacked in by looking at the name of the weapons but that feels smelly. Open for suggestions here.

For the button captions I added an English (I heard that in navy speech firing a ship weapon is not called "fire a weapon" but rather "weapons release" but maybe a native speaker can comment on that) and a German version. The other languages are auto translated so they should be checked by native speakers.

Resolves #191.

ToDos
- [ ] Discuss color scheme
- [ ] Discuss translations
- [ ] More testing

Bildschirmfoto 2023-01-11 um 14 20 50

Bildschirmfoto 2023-01-11 um 14 20 17

### CODE REVIEW

**Comment by IrishWolf** [comment]
Looks great!

> * The "disabled" button gets a gray color instead of red (since red should usually indicate danger or errors and gray usually indicates a disabled state)

Red is in this regard rational because the module is usually not deactivated but destroyed.
But I understand your idea behind it and I think thats not the biggest problem.

Just an idea:
How about streamlining the whole module-layout with the rest of the sheets?
_(just an dummy)_
image

**Comment by gkahn84** [comment]
@IrishWolf Thanks! You're right, red makes more sense in that case. I like your idea of streamlining the module layout with the rest of the sheets better anyway (also no need for a third color then). @AlexOkafor What do you think?

**Comment by AlexOkafor** [comment]
> @IrishWolf Thanks! You're right, red makes more sense in that case. I like your idea of streamlining the module layout with the rest of the sheets better anyway (also no need for a third color then). @AlexOkafor What do you think?

Yes, I agree with those two sentiments as well! Every time I looked at the module section I was wanting to revamp it to the standard list but haven't had the time to dig into it. I had different plans for it that just never came to light, so I think consistency in UX here wins the day.

**Comment by gkahn84** [comment]
Great, I'm happy to look into it as soon as I find the time.

**Pull request closed without merging**
