### PR TITLE
Actor rolls implementation for yzecoriolis 3.3.0

### PR DESCRIPTION
**Pull request by kbender84**
I have added functionality for external skill rolls for yzecoriolis (I am using it in my Coriolis Action Hud module).
please verify the code if it works and if possible integrate into main branch

### CODE REVIEW

**Comment by AlexOkafor** [comment]
Hi @kbender84! Thanks for the PR. I'm wanting to understand the changes a bit more clearly. Since this is a module that sits on top of Coriolis, I'm wondering what portion of this code could not just be part of the module itself rather than core to the system? Is there some limitation this is working around?

**Comment by kbender84** [comment]
Hi, I'm back from vacation :)
Sooooo... the basic yzecoriolis has external function that allows to call game.yzecoriolis.rollItemMacro(actionId); to generate item/skill roll.
What I found missing was a function that would allow to do pure skill and attribute rolls. 
I could try to rewrite it as part of my module with imports/extends (I'm not good at JavaScript, but I thing I could handle it), but I thought I would be nice for other modules and also gamemasters to call direct actor skill/attribute rolls from macro/UI.

My changes are following:
yzecoriolis is used to expose rollActorMacro to the world
actor.js is modified with a function to handle skill / attribute rolls and pass the results to game chat.

**Comment by kbender84** [comment]
Hi @AlexOkafor - maybe we could chat on Discord? That would probably be more time effective :)

**Comment by kbender84** [comment]
Hi @AlexOkafor - would you have some time to talk about this pull request? I can explain the changes in details, but would be probably easier to do that via chat or call.

**Comment by kbender84** [comment]
Pinging it so it does not get closed :)

**Comment by kbender84** [comment]
I have managed eveyrhting on my side, so this is no longer needed.

**Pull request closed without merging**
