### PR TITLE
item stylings, item Modifiers, ship module-rework, roll-modifier-rework

### LINKED ISSUE #37: Support permanent stress reductions
some die rolls can permanently damage a person's max mind points pool. need to add a tracker to that.

### LINKED ISSUE #160: Item configuration
Similar to the attached screenshot of the Forbidden Lands system, allow Items to be configured beyond just modifying Hit Points and/or Mind Points.  Any item, whether it's a Talent, or weapon, or armor, etc., should be configurable to add modifiers to (or based on) any attribute, skill, talent, etc.

The modifiers defined for these items should only take effect when the item is ACTIVE or EQUIPPED.

image

### LINKED ISSUE #249: encumbrance can not be adjusted
Currently, having a cyberimplant like _Endo Skeleton_ does not double the carrying capacity. I understand that's because items have defined bonuses (HP, MP) and are not special cased. In some cases it wouldn't even make sense because some bonuses are not fixed and depend on narrative decisions (like the Endo Skeleton +2 to Force for heavy lifting). But in this case it is a fixed value that doesn't depend on external circumstances, so it'd be useful to have it reflected in the character sheet.

The problem is that there's no way to change it manually (in the charsheet), because encumbrance is always computed directly from Strength.

### PR DESCRIPTION
**Pull request by IrishWolf**
resolves #160, resolves #37, resolves  #249
Finnishing of #209 / #235 

well.. that is more than I had anticipated... 😅

---

### slightly stylings
changed a few checkboxes within talents, gear etc
image

---

### ship-module rework
No the styling of ship-modules is fitting to the rest of the system.
Also you can roll from the weapons directly.
For the weapon-rolling are some conditions:
* weapon must be enabled
* there must be at least 1 crewmember
* you must controll at least 1 crewmember
  * if you can control more than 1 it will ask you with which one you want to roll
  * sum of attr.+skill must over 0

image

---

### Ship value & debt
I discovered, that there were already data-fields for the paidOff and balance-part of the ship-costs.
So I implemented that for a visible UI.
* The Ship Cost is now the ship Value (needed for supply/maintenance-calculations)
* Within the Logbok you can now write yor debts, paid offs and the sheet will tell you your balance (neat overview).

image

---

### item Modificators
Finnishing of #235 
Now with: 
* added calculation/give options for rolls (attributes, skills, weapons, armor, ship-rolls)
* added modifiers to advanced-roll infos

---

### roll visibility
#251 just worked for characters/npc. Ship-rolls weren't influenced (but asked).
This is fixxed, too.

---

### Rework of roll-dialog
For the ship-module rolling and the item modifcators it was necessary to rework the whole dialog.
Here is a short video which shows the combination of modifiers, ship-crew and the new roll-dialog.
https://cdn.discordapp.com/attachments/419501303744430081/1222986382109179905/Coriolis_-_Kampagne_Foundry_Virtual_Tabletop_2024-03-28_20-06-45.mp4?ex=661835d3&is=6605c0d3&hm=06a7fff4d863a6dc3324aad97a339b8a1b0d7e79c0c4dfb40c3f17edb793314a&

---

### Questions and considerations
* should gear-modifiers only show up as option within rolls when equipped?
* does ship-modules/-features/-damages should give itemModifiers?

### CODE REVIEW

**Comment by Animator369** [comment]
can you add a ship armor roll in ship sheet?

**Comment by IrishWolf** [comment]
> can you add a ship armor roll in ship sheet?

good idea, but the question would be where the roll-button could be placed. 🤔

**Comment by Animator369** [comment]
> good idea, but the question would be where the roll-button could be placed. 🤔

where word "Armor", maybe?

**Comment by IrishWolf** [comment]
> where word "Armor", maybe?

Not enough space I would say.
And not intuitive as everything else there is just inputs/numbers.

Maybe something like a fake-crew-member? 🤔
Regularly everyone would roll their position from there too (besides the gunner now XD)
But could maybe a space-problem too if you have a big crew 🤔

**Comment by Animator369** [comment]
> Not enough space I would say. And not intuitive as everything else there is just inputs/numbers.
> 
> Maybe something like a fake-crew-member? 🤔 Regularly everyone would roll their position from there too (besides the gunner now XD) But could maybe a space-problem too if you have a big crew 🤔

what if add tab "options" after "notes" and move inputs to there, this inputs uses one times per 15-20 sessions or less, and after that we have more space for crew tab and for other tabs.

**Comment by IrishWolf** [comment]
> what if add tab "options" after "notes" and move inputs to there, this inputs uses one times per 15-20 sessions or less, and after that we have more space for crew tab and for other tabs.

Would be an option. Or move this to the image-overlay like the class and shipyard.
What does @AlexOkafor or @coderunner think?

**Comment by IrishWolf** [comment]
Moved the discussion about the armor-rolls to a separate issue #259 to discuss

**Pull request merged**
